#====================================
#              変数
#====================================

# @baseurl = https://challenge-your-limits.herokuapp.com
@baseurl = http://localhost:8000/api
@name = sample_sample_02
@email = sample_sample_02@gmail.com

#====================================
#
#====================================

# GET https://challenge-your-limits.herokuapp.com
GET {{baseurl}}/call/me

###
POST {{baseurl}}/call/me

###

POST {{baseurl}}/challenge_users

###

# 「content-type」の下は１行空けないといけないみたい。
POST {{baseurl}}/challenge_users
content-type: application/json

{
    "name": "{{name}}",
    "email": "{{email}}"
}


